### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by Bigshmow** [ppgeyser/plant-parenthood#7]
<s>This was not contained in the brainstorming materials but figured our login page should have some type of </s> Jumbotron/Banner at the top.
- [x] Jumbotron/Banner

Likely containing our brand name and image, possibly a mission statement.  KISS, though.

**Comment by Bigshmow** [comment]
Thinking we might also want to populate this landing/login page with a "here's what we offer" section.  Something that shows a breakdown sample of the survey, dashboard, plant details page.

- [ ] Breakdown Card
  - [ ] Survey Card
  - [ ] Dashboard Card
  - [ ] Plant Details Card

Just thinking from a user experience POV, someone probably wants to see what's available to them at a glance.  What do you all think?

**Comment by Zuzanav** [comment]
Added banner to Landing Page - Not complete as it needs the following: 

- [ ] new image

- [ ] placed into a jumbotron or card
